version: 1

formatters:
  normal:
    style: '{'
    format: '[{asctime}] {levelname: >8} - {name}: {message}'
    datefmt: '%H:%M:%S'
  threaded:
    style: '{'
    format: '[{asctime}] {levelname: >8} - {threadName} - {name}: {message}'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: normal
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]