version: 1

formatters:
  normal:
    style: '{'
    format: '[{asctime}] {levelname: >8} - {name}: {message}'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: normal
  file:
    class: logging.FileHandler
    filename: training.log
    mode: w
    level: DEBUG
    formatter: normal

root:
  level: DEBUG
  handlers: [console, file]